Fix typescript error
This fixes the problem: node_modules/@aws-amplify/auth/src/providers/cognito/utils/oauth/getRedirectUrl.ts:42:10 - error TS2869: Right operand of ?? is unreachable because the left operand is never nullish.